name: Branch Name Check
on:
  create:
  push:
  pull_request:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Убедитесь, что для pull request выгружается коммит исходной ветки
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Загрузка веток develop и main
        run: |
          # Загрузка develop и main из целевого репозитория
          git fetch origin develop:refs/remotes/origin/develop || echo "⚠️ Ветка develop не найдена, пропускаем"
          git fetch origin main:refs/remotes/origin/main || echo "⚠️ Ветка main не найдена, пропускаем"
          # Для pull request явно загружаем исходную ветку
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            git fetch origin ${{ github.event.pull_request.head.ref }}:refs/remotes/origin/${{ github.event.pull_request.head.ref }}
          fi

      - name: Проверка имени ветки и источника
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            BRANCH_NAME="$GITHUB_HEAD_REF"
            # Используем HEAD исходной ветки для pull request
            BRANCH_REF="origin/$GITHUB_HEAD_REF"
          else
            BRANCH_NAME="$GITHUB_REF_NAME"
            BRANCH_REF="$GITHUB_REF_NAME"
          fi

          if [[ "$BRANCH_NAME" == "develop" || "$BRANCH_NAME" == "main" ]]; then
            echo "ℹ️ Ветка $BRANCH_NAME не требует проверки"
            exit 0
          fi

          FEATURE_PATTERN="^feature/QW-[0-9]+-[a-z0-9-]+$"
          RELEASE_PATTERN="^release/[0-9]+\.[0-9]+\.[0-9]+$"
          FIX_PATTERN="^fix/QW-[0-9]+-[a-z0-9-]+$"

          ERROR_MSG="❌ Неверный формат ветки или источник! Требования:
          1. Feature: feature/QW-<id>-<описание> (например, feature/QW-123-user-profile)
             - Ответвляется от develop или main
          2. Release: release/<версия> (например, release/1.3.0)
             - Ответвляется от develop или main
          3. Fix: fix/QW-<id>-<описание> (например, fix/QW-456-login-security)
             - Ответвляется от develop или main
          Имя ветки: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ $FEATURE_PATTERN ]]; then
            echo "🔍 Ветка $BRANCH_NAME — feature"
            EXPECTED_SOURCE="develop|main"
          elif [[ "$BRANCH_NAME" =~ $RELEASE_PATTERN ]]; then
            echo "🔍 Ветка $BRANCH_NAME — release"
            EXPECTED_SOURCE="develop|main"
          elif [[ "$BRANCH_NAME" =~ $FIX_PATTERN ]]; then
            echo "🔍 Ветка $BRANCH_NAME — fix"
            EXPECTED_SOURCE="develop|main"
          else
            echo "$ERROR_MSG"
            echo "❌ Ветка не соответствует ни одному шаблону"
            exit 1
          fi

          # Используем merge-base без --fork-point для надежности
          SOURCE_BRANCH=$(git merge-base "$BRANCH_REF" origin/develop 2>/dev/null || git merge-base "$BRANCH_REF" origin/main 2>/dev/null || true)
          if [ -z "$SOURCE_BRANCH" ]; then
            echo "$ERROR_MSG"
            echo "❌ Не удалось определить источник ветки $BRANCH_NAME (ветки develop или main могут отсутствовать)"
            exit 1
          fi

          if git merge-base --is-ancestor "$SOURCE_BRANCH" origin/develop 2>/dev/null; then
            echo "✅ Ветка $BRANCH_NAME ответвлена от develop"
          elif git merge-base --is-ancestor "$SOURCE_BRANCH" origin/main 2>/dev/null; then
            echo "✅ Ветка $BRANCH_NAME ответвлена от main"
          else
            echo "$ERROR_MSG"
            echo "❌ Ветка $BRANCH_NAME не ответвлена от develop или main"
            exit 1
          fi

          echo "✅ Все проверки пройдены для ветки $BRANCH_NAME"
