name: Conventional Commits Check
on: [push, pull_request]

jobs:
  check-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate commit messages
        run: |
          TYPES="chore|docs|feat|fix|refactor|revert|style|test"
          HEADER_PATTERN="^($TYPES)(\([a-z0-9-]+\))?:[[:space:]]*.+"
          FOOTER_PATTERN="^Fixes:[[:space:]]*[A-Z]+-[0-9]+$"
          
          ERROR_MSG="❌ Неверный формат коммита! Требования:
          1. Первая строка: <тип>(<область>): <описание>
             Пример: 'fix: исправить баг' или 'feat(api): добавить метод'
             Допускается: 'fix: fix regex'
          2. Последняя строка: 'Fixes: QW-52' (обязательно)
          3. Между ними может быть любой текст (игнорируется)"

          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            COMMIT_SHAS=$(git rev-list --no-merges $GITHUB_SHA^..$GITHUB_SHA)
          else
            COMMIT_SHAS=$(git rev-list --no-merges origin/$GITHUB_BASE_REF..$GITHUB_HEAD_REF)
          fi

          for sha in $COMMIT_SHAS; do
            commit=$(git log -1 --format=%B "$sha")
            echo "🔍 Проверяем коммит $sha:"
            echo "---"
            echo "$commit"
            echo "---"
            
            cleaned_commit=$(echo "$commit" | sed '/^$/d')
            first_line=$(echo "$cleaned_commit" | head -n 1)
            last_line=$(echo "$cleaned_commit" | tail -n 1)
            
            if [ -z "$first_line" ] || [ -z "$last_line" ]; then
              echo "❌ Ошибка: коммит пустой или не содержит ожидаемых строк"
              echo "---"
              echo "$commit"
              echo "---"
              echo "$ERROR_MSG"
              exit 1
            fi
            
            if ! [[ "$first_line" =~ $HEADER_PATTERN ]] || ! [[ "$last_line" =~ $FOOTER_PATTERN ]]; then
              echo "❌ Ошибка в коммите $sha:"
              echo "---"
              echo "$commit"
              echo "---"
              echo "$ERROR_MSG"
              exit 1
            fi
            echo "✅ Коммит $sha валиден"
          done
