name: Conventional Commits Check (All Branches)
 on:
   push:
   pull_request:
 
 jobs:
   check-commits:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
       - name: Validate commit messages
         run: |
           PATTERN='^(chore|docs|feat|fix|refactor|revert|style|test)(\([a-z-]+\))?: [A-Z][a-zA-Z0-9 -]+(\n\n.*)?(\n\nFixes: [A-Z]+-[0-9]+)?$'
           ERROR_MSG="❌ Invalid commit format! Use:\n<type>(<scope>): <Subject> (imperative mood)\n\n<body> (optional)\n\nFixes: TASK-123\n\nПример:\nfix(login): Resolve 500 error\n\nИз-за неправильной валидации...\n\nFixes: QW-45"
           
           if [ "$GITHUB_EVENT_NAME" = "push" ]; then
             BASE_SHA=$(git rev-parse $GITHUB_REF~1)
             HEAD_SHA=$(git rev-parse $GITHUB_SHA)
           elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
             BASE_SHA=$(git rev-parse $GITHUB_BASE_REF)
             HEAD_SHA=$(git rev-parse $GITHUB_HEAD_REF)
           fi
 
           git log --format=%B $BASE_SHA..$HEAD_SHA | while read -r line; do
             if [ -n "$line" ] && [[ ! "$line" =~ ^# ]] && [[ ! "$line" =~ ^$PATTERN ]]; then
               echo -e "$ERROR_MSG"
               echo "Найден невалидный коммит: $line"
               exit 1
             fi
           done
