name: Update Submodules
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update submodules
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git submodule update --remote --recursive
          git add .
          
          # Проверяем, есть ли изменения
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "chore(submodules): auto-update"
            git push
          else
            echo "Нет изменений в субмодулях."
          fi
